# Generated by Django 5.2.4 on 2025-07-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greentech", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("logo_url", models.URLField()),
                ("website_url", models.URLField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
