# Generated by Django 5.2.4 on 2025-07-23 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greentech", "0002_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="greenproduct",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="greentech.brand",
            ),
        ),
        migrations.AlterField(
            model_name="greenproduct",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="greenproduct",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
