# Generated by Django 5.2.4 on 2025-07-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greentech", "0003_greenproduct_brand_alter_greenproduct_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="card_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
