# Generated by Django 5.2.4 on 2025-07-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("greentech", "0003_userprofile_country_gender"),
        ("greentech", "0004_brand_card_image_url"),
    ]

    operations = []
