# Generated by Django 5.2.4 on 2025-07-28 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greentech", "0008_securityquestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="securityquestion",
            name="question_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="securityquestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="securityquestion",
            unique_together={("user", "question_number")},
        ),
    ]
